apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackathon-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    ingress.gcp.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:

          # Route to node-service-1
          - path: /service1
            pathType: Prefix
            backend:
              service:
                name: node-service-1-svc
                port:
                  number: 80

          # Route to node-service-2
          - path: /service2
            pathType: Prefix
            backend:
              service:
                name: node-service-2-svc
                port:
                  number: 80

          # Route to java-service
          - path: /java
            pathType: Prefix
            backend:
              service:
                name: java-service-svc
                port:
                  number: 80
