# Service: node-service-1
apiVersion: v1
kind: Service
metadata:
  name: node-service-1-svc
spec:
  type: ClusterIP
  selector:
    app: node-service-1
  ports:
    - port: 80
      targetPort: 3001

---
# Service: node-service-2
apiVersion: v1
kind: Service
metadata:
  name: node-service-2-svc
spec:
  type: ClusterIP
  selector:
    app: node-service-2
  ports:
    - port: 80
      targetPort: 3002

---
# Service: java-service
apiVersion: v1
kind: Service
metadata:
  name: java-service-svc
spec:
  type: ClusterIP
  selector:
    app: java-service
  ports:
    - port: 80
      targetPort: 8080
