name: CD Deploy Order Service to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: hackathon-cluster
        location: us-central1-a

    - name: Deploy Order Service
      run: |
        kubectl apply -f k8s/deployment/deployment-order-service.yaml

    - name: Verify Pods
      run: kubectl get pods
