name: CI Pipeline - Build & Push to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGION: us-central1
      REPO_NAME: hackathon-repo

    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Setup gcloud SDK
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # Step 4: Configure Docker for Artifact Registry
      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      # -------------------------------
      # ✅ Build & Push Java Order Service
      # -------------------------------
      - name: Build & Push Order Service Image
        run: |
          IMAGE="$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO_NAME/order-service"
          IMAGE="$REGION-docker.pkg.dev/mani-hackathon/$REPO_NAME/order-service"

          echo "Building Order Service..."
          docker build -t $IMAGE:latest ./order-service

          echo "Tagging with Commit SHA..."
          docker tag $IMAGE:latest $IMAGE:${{ github.sha }}

          echo "Pushing Images..."
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}

      # ✅ Build & Push Node Appointment Service
      # -------------------------------
      - name: Build & Push Appointment Service Image
        run: |
          IMAGE="$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO_NAME/appointment-service"
          IMAGE="$REGION-docker.pkg.dev/mani-hackathon/$REPO_NAME/appointment-service"

          echo "Building Appointment Service..."
          docker build -t $IMAGE:latest ./appointment-service

          echo "Tagging with Commit SHA..."
          docker tag $IMAGE:latest $IMAGE:${{ github.sha }}

          echo "Pushing Images..."
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}

      # ✅ Final Success Message
      - name: CI Completed Successfully
        run: echo "All Microservices Built & Pushed to Artifact Registry ✅"
